apiVersion: v1
kind: Service
metadata:
  name: random-number-app-service1
spec:
  selector:
    app: random-number-app
  ports:
    - protocol: TCP
      port: 80 # Port on which the service will be accessible
      targetPort: 8080 # Port on which the Java app inside the pods is running
  type: ClusterIP


---
  --- 
apiVersion: v1
kind: Service
metadata:
  name: random-number-app-service2
spec:
  type: NodePort
  ports:
    - port: 8082
      protocol: TCP
      targetPort: 8080
  selector:
    app: random-number-app 

# kubectl apply -f app-service.yaml 