apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-number-app
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: random-number-app
  template:
    metadata:
      labels:
        app: random-number-app
    spec:
      containers:
      - name: random-number-app
        image: albapupli/devops-project:latest # Update with your Docker image details
        imagePullPolicy: Always
        ports:
        - containerPort: 8080 # Adjust port if your Java app listens on a different port
        volumeMounts:
        - name: logs
          mountPath: /var/logs
    volumes:
      - name: logs
        hostPath: 
          path: /var/logs
          type: DirectoryOrCreate



        # apply in docker desktop using these commands
        # kubectl apply -f deployment.yaml
        # kubectl apply -f service.yaml
