apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer # Use "LoadBalancer" for Docker Desktop Kubernetes, "NodePort" for other setups

  ---

# grafana-service.yaml
#apiVersion: v1
#kind: Service
#metadata:
 # name: grafana-service
#spec:
 # selector:
  #  app: grafana
  #ports:
   # - protocol: TCP
    #  port: 3000
     # targetPort: 3000
  #type: NodePort  # Use "LoadBalancer" for Docker Desktop Kubernetes, "NodePort" for other setups


  #After applying these configurations, you should be able to access 
  #Prometheus at http://<Node-IP>:<NodePort> and 
  #Grafana at http://<Node-IP>:<NodePort> (default credentials for Grafana are admin/admin).