# prometheus-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-configmap
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s

    scrape_configs:
    - job_name: 'java-app'
      static_configs:
      - targets: ['java-app-service:8080']

# apply configs using:
# kubectl apply -f prometheus-configmap.yaml
# kubectl apply -f prometheus-deployment.yaml
# kubectl apply -f prometheus-service.yaml
# kubectl apply -f grafana-deployment.yaml
# kubectl apply -f grafana-service.yaml
