# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven # name of prj

# checks if there are any push or pull req on master branch, then do the following (executes line 18)
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest #operating system it is run on

    steps:
    - uses: actions/checkout@v3 # checks the dockerfile in order to build t6he docker img so checks for repo in there
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Publish to Docker Hub
      uses: docker/build-push-action@v1  
      with:       
        username: ${{ secrets.DOCKER_USERNAME }} 
        password:  ${{ secrets.DOCKER_PASSWORD }}
        repository: albapupli/devops-project     
        tags: ${{github.run_number}}
    
  # deploy:
    # runs-on: ubuntu-18.04
    #needs: build

    #steps:
    #- uses: actions/checkout@v3
    #- name: login to docker
    #- uses: docker/login-action@v1
     # with:
      #  username: ${{ secrets.DOCKER_HUB_USERNAME }}
       # password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    
    #- name: docker push
     # run: docker push albapupli/devops-project:docker_img
    
    
    #- name: Build and push Docker Img
     # uses: docker/build-push-action@v1
      #with:
       # registry: docker.io
        #dockerfile: Dockerfile
        #username: ${{ secrets.DOCKER_HUB_USERNAME }}
        #password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        #repository: albapupli/devops-project # repo of dockerhub
        #push: true
      #run:
        #docker build -t albapupli/docker-project:<docker image for devops project>
        #docker login -u $DOCKER_HUB_USERNAME -p DOCKER_HUB_PASSWORD
        #docker push albapupli/docker-project:<docker image for devops project>
